version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: bragger
    main: ./cmd/bragger
    binary: bragger
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: bragger
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

brews:
  - name: bragger
    repository:
      owner: ewurch
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/ewurch/bragger"
    description: "Job application tracker and AI-powered resume generator"
    license: "MIT"
    install: |
      bin.install "bragger"
    test: |
      system "#{bin}/bragger", "version"

release:
  github:
    owner: ewurch
    name: bragger
  draft: false
  prerelease: auto
